services:
  - type: web
    name: trading-bot-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn webhook_server.main:app --host 0.0.0.0 --port 8000"
    plan: free
    envVars:
      - key: API_KEY
        value: tradingview_webhook_uk_bot
      - key: SECRET_KEY
        value: 3a18b037-0aab-498b-9f30-3a3631a4726e
      - key: BINANCE_API_KEY
        value: bab069becbab05b20c2b2b54b76b956b4a691c376138c62a7f7bfb266eb65016
      - key: BINANCE_API_SECRET
        value: a8255f8af137b4bae0082dc015d4e8518584eb9e7413adfbf37772c3978ee5ae
      - key: USE_TESTNET
        value: true
      - key: SYMBOLS
        value: XRPUSDT,SUIUSDT,ENAUSDT,PEPEUSDT,TRXUSDT
      - key: MAX_POSITION_SIZE
        value: 0.01
      - key: COOLDOWN_SECONDS
        value: 60
      - key: MAX_POSITION_SIZE_SUI
        value: 252
      - key: MAX_POSITION_SIZE_XRP
        value: 252
      - key: MAX_POSITION_SIZE_ENA
        value: 252
